if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/codeeditor/CMakeLists.txt)
    add_subdirectory(codeeditor)
endif()
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/codepdfprinter/CMakeLists.txt)
    add_subdirectory(codepdfprinter)
endif()
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/minimaltest/CMakeLists.txt)
    add_subdirectory(minimaltest)
endif()
